name: Deploy React App to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. GitHub 저장소를 클론
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Node.js를 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. 프로젝트 의존성 설치
      - name: Install dependencies
        run: yarn

      # 4. 프로젝트 빌드 및 빌드 파일 확인
      - name: Build project
        run: yarn build

      # 5. 빌드된 정적 파일을 gh-pages 브랜치에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
